### ISSUE TITLE
Please consider License seriously

### ISSUE THREAD

**Issue by VinhLoiIT** [phamdinhkhanh/general_ocr#2]
I found that your repository is based on the `mmocr` repo of OpenMMLab (https://github.com/open-mmlab/mmocr). Please at least cite the repo and preserve the copyrights before redistribution to acknowledge the authors' works.

Thanks.

**Comment by phamdinhkhanh** [comment]
Hello you. mmocr is only one resource I refer from because I do not enough resources to train models. I design it based on the design pattern of facebook/Detectron and openmm-cv and I refer to its right in introduction. In specifically, I get layers code from openmm-cv, workflow from facebook/Detectron. If you thoroughly scan you can see my package is bigger than mmocr when it supports more package and layers than. In the future, I plan to re-implement more SOTA models based on this design such as paddleOCR, TR-OCR, TessaractOCR.
